kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
      - grafana.flowgenie.de
      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.flowgenie.de
    additionalDataSources:
    - name: Loki
      type: loki
      url: http://monitoring-system-loki:3100
