jellyfin:
  ingress:
    main:
      enabled: true
      hosts:
      - host: jellyfin.flowgenie.de
      tls:
      - secretName: jellyfin-tls-certificate
        hosts:
        - jellyfin.flowgenie.de
