metal:
  children:
    masters:
      hosts:
        # node03: {ansible_host: 192.168.3.103, mac: 'D0:67:E5:2F:C2:98'}
        node02: {ansible_host: 192.168.3.102, mac: '10:78:D2:C3:DD:AC'}
    workers:
      hosts:
        node01: {ansible_host: 192.168.3.101, mac: 'FC:4D:D4:31:F0:C8'}
        
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
