metal:
  children:
    masters:
      hosts:
        # metal0: {ansible_host: 192.168.1.110, mac: '00:23:24:d1:f3:f0'}
        metal1: {ansible_host: 192.168.1.111, mac: '00:23:24:d1:f4:d6'}
        metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60'}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f5:69'}
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
