- name: Start PXE server
  hosts: localhost
  roles:
    - pxe-server

- name: Provision bare metal machines
  hosts: metal
  gather_facts: no
  roles:
    - wake

- name: Create Kubernetes cluster
  hosts: metal
  roles:
    - k3s
