vault:
  injector:
    enabled: false
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
      - host: vault.flowgenie.de
      tls:
      - secretName: vault-tls-certificate
        hosts:
        - vault.flowgenie.de
    dev:
      enabled: true # TODO disable vault dev mode
