gitea:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    hosts:
      - host: git.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
    - secretName: gitea-tls-certificate
      hosts:
        - git.khuedoan.com
  gitea:
    config:
      server:
        LANDING_PAGE: explore
