syncthing:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
      - host: syncthing.t-hom.net
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: syncthing-tls-certificate
        hosts:
        - syncthing.t-hom.net
  persistence:
    data:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
